CLASS z2ui5_cl_core_srv_util DEFINITION
  PUBLIC
  INHERITING FROM z2ui5_cl_util
  CREATE PUBLIC.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS Z2UI5_CL_CORE_SRV_UTIL IMPLEMENTATION.
ENDCLASS.
