PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCJ_Z2UI5_SCREEN CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCJ_Z2UI5_SCREEN-APPL .
    FIELD ZCJ_Z2UI5_SCREEN-SCREEN .
    FIELD ZCJ_Z2UI5_SCREEN-SEQNR .
    FIELD ZCJ_Z2UI5_SCREEN-DIALOG .
    FIELD ZCJ_Z2UI5_SCREEN-POPOVER .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   CHAIN.
    FIELD ZCJ_Z2UI5_SCREET-SDESCR .
    MODULE SET_TXT_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCJ_Z2UI5_SCREEN-APPL .
    FIELD ZCJ_Z2UI5_SCREEN-SCREEN .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
