PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZMV_CJ_LAY CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
 MODULE FILL_SUBSTFLDS.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZMV_CJ_LAY-BLOCK_ID .
    FIELD ZMV_CJ_LAY-ELEM_ID .
    FIELD ZMV_CJ_LAY-KIND .
    FIELD ZMV_CJ_LAY-ROW_NO .
    FIELD ZMV_CJ_LAY-COL_START .
    FIELD ZMV_CJ_LAY-COL_SPAN .
    FIELD ZMV_CJ_LAY-LABEL_SPAN .
    FIELD ZMV_CJ_LAY-FLOW .
    FIELD ZMV_CJ_LAY-INLINE .
    FIELD ZMV_CJ_LAY-HIDDEN .
    FIELD ZMV_CJ_LAY-FIXED .
    FIELD ZMV_CJ_LAY-ALIGN .
    FIELD ZMV_CJ_LAY-WIDTH .
    FIELD ZMV_CJ_LAY-CHANGED_BY .
    FIELD ZMV_CJ_LAY-CHANGED_AT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZMV_CJ_LAY-BLOCK_ID .
    FIELD ZMV_CJ_LAY-ELEM_ID .
    FIELD ZMV_CJ_LAY-KIND .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
