*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZMV_CJ_LAY......................................*
FORM GET_DATA_ZMV_CJ_LAY.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZRAK_T_JNY WHERE
(VIM_WHERETAB) .
    CLEAR ZMV_CJ_LAY .
ZMV_CJ_LAY-MANDT =
ZRAK_T_JNY-MANDT .
ZMV_CJ_LAY-JOURNEY_ID =
ZRAK_T_JNY-JOURNEY_ID .
<VIM_TOTAL_STRUC> = ZMV_CJ_LAY.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZMV_CJ_LAY .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZMV_CJ_LAY.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZMV_CJ_LAY-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZRAK_T_JNY WHERE
  JOURNEY_ID = ZMV_CJ_LAY-JOURNEY_ID .
    IF SY-SUBRC = 0.
    DELETE ZRAK_T_JNY .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZRAK_T_JNY WHERE
  JOURNEY_ID = ZMV_CJ_LAY-JOURNEY_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZRAK_T_JNY.
    ENDIF.
ZRAK_T_JNY-MANDT =
ZMV_CJ_LAY-MANDT .
ZRAK_T_JNY-JOURNEY_ID =
ZMV_CJ_LAY-JOURNEY_ID .
    IF SY-SUBRC = 0.
    UPDATE ZRAK_T_JNY ##WARN_OK.
    ELSE.
    INSERT ZRAK_T_JNY .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZMV_CJ_LAY-UPD_FLAG,
STATUS_ZMV_CJ_LAY-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZMV_CJ_LAY.
  SELECT SINGLE * FROM ZRAK_T_JNY WHERE
JOURNEY_ID = ZMV_CJ_LAY-JOURNEY_ID .
ZMV_CJ_LAY-MANDT =
ZRAK_T_JNY-MANDT .
ZMV_CJ_LAY-JOURNEY_ID =
ZRAK_T_JNY-JOURNEY_ID .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZMV_CJ_LAY USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZMV_CJ_LAY-JOURNEY_ID TO
ZRAK_T_JNY-JOURNEY_ID .
MOVE ZMV_CJ_LAY-MANDT TO
ZRAK_T_JNY-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZRAK_T_JNY'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZRAK_T_JNY TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZRAK_T_JNY'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
