PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZMV_JNY_RULE CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
 MODULE FILL_SUBSTFLDS.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZMV_JNY_RULE-RULE_ID .
    FIELD ZMV_JNY_RULE-SRC_FIELD .
    FIELD ZMV_JNY_RULE-SRC_OP .
    FIELD ZMV_JNY_RULE-SRC_VALUE .
    FIELD ZMV_JNY_RULE-ACTION_TYPE .
    FIELD ZMV_JNY_RULE-TGT_FIELD .
    FIELD ZMV_JNY_RULE-TGT_VALUE .
    FIELD ZMV_JNY_RULE-TOTABLE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZMV_JNY_RULE-RULE_ID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
