PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZRAK_T_JNY CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZRAK_T_JNY-JOURNEY_ID .
    FIELD ZRAK_T_JNY-TITLE .
    FIELD ZRAK_T_JNY-CJ_TYPE .
    FIELD ZRAK_T_JNY-LAYOUT_MODE .
    FIELD ZRAK_T_JNY-THEME_VARIANT .
    FIELD ZRAK_T_JNY-ACCENT_TYPE .
    FIELD ZRAK_T_JNY-BRAND_COLOR .
    FIELD ZRAK_T_JNY-NAVY_COLOR .
    FIELD ZRAK_T_JNY-DENSITY .
    FIELD ZRAK_T_JNY-SUBTITLE .
    FIELD ZRAK_T_JNY-SHOW_ACTIONS .
    FIELD ZRAK_T_JNY-HANDLER_CLASS .
    FIELD ZRAK_T_JNY-ACTIVE .
    FIELD ZRAK_T_JNY-TITLE_AR .
    FIELD ZRAK_T_JNY-SUBTITLE_AR .
    FIELD ZRAK_T_JNY-BKND_ACTIVE .
    FIELD ZRAK_T_JNY-BKND_CATEGORY .
    FIELD ZRAK_T_JNY-BKND_FM_POST .
    FIELD ZRAK_T_JNY-BKND_FM_READ .
    FIELD ZRAK_T_JNY-BKND_JOURNEY .
    FIELD ZRAK_T_JNY-TILE_CODE .
    FIELD ZRAK_T_JNY-CHANGED_BY .
    FIELD ZRAK_T_JNY-CHANGED_AT .
    FIELD ZRAK_T_JNY-THEME_OWN .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZRAK_T_JNY-JOURNEY_ID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
