*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZMV_JNY_FIELD...................................*
FORM GET_DATA_ZMV_JNY_FIELD.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZRAK_T_JNY_FLD WHERE
(VIM_WHERETAB) .
    CLEAR ZMV_JNY_FIELD .
ZMV_JNY_FIELD-MANDT =
ZRAK_T_JNY_FLD-MANDT .
ZMV_JNY_FIELD-JOURNEY_ID =
ZRAK_T_JNY_FLD-JOURNEY_ID .
ZMV_JNY_FIELD-STEP_ID =
ZRAK_T_JNY_FLD-STEP_ID .
ZMV_JNY_FIELD-FIELD_NAME =
ZRAK_T_JNY_FLD-FIELD_NAME .
ZMV_JNY_FIELD-SEQNR =
ZRAK_T_JNY_FLD-SEQNR .
ZMV_JNY_FIELD-ZLABEL =
ZRAK_T_JNY_FLD-ZLABEL .
ZMV_JNY_FIELD-FTYPE =
ZRAK_T_JNY_FLD-FTYPE .
ZMV_JNY_FIELD-PLACEHOLDER =
ZRAK_T_JNY_FLD-PLACEHOLDER .
ZMV_JNY_FIELD-DEFAULT_VAL =
ZRAK_T_JNY_FLD-DEFAULT_VAL .
ZMV_JNY_FIELD-FGROUP =
ZRAK_T_JNY_FLD-FGROUP .
ZMV_JNY_FIELD-ZSECTION =
ZRAK_T_JNY_FLD-ZSECTION .
ZMV_JNY_FIELD-FSTATE =
ZRAK_T_JNY_FLD-FSTATE .
ZMV_JNY_FIELD-WIDTH =
ZRAK_T_JNY_FLD-WIDTH .
ZMV_JNY_FIELD-HIDDEN =
ZRAK_T_JNY_FLD-HIDDEN .
ZMV_JNY_FIELD-READONLY =
ZRAK_T_JNY_FLD-READONLY .
ZMV_JNY_FIELD-REQUIRED =
ZRAK_T_JNY_FLD-REQUIRED .
ZMV_JNY_FIELD-REGEX =
ZRAK_T_JNY_FLD-REGEX .
ZMV_JNY_FIELD-MIN_LEN =
ZRAK_T_JNY_FLD-MIN_LEN .
ZMV_JNY_FIELD-MAX_LEN =
ZRAK_T_JNY_FLD-MAX_LEN .
ZMV_JNY_FIELD-MIN_VAL =
ZRAK_T_JNY_FLD-MIN_VAL .
ZMV_JNY_FIELD-MAX_VAL =
ZRAK_T_JNY_FLD-MAX_VAL .
ZMV_JNY_FIELD-MSG =
ZRAK_T_JNY_FLD-MSG .
ZMV_JNY_FIELD-HAS_ATTACH =
ZRAK_T_JNY_FLD-HAS_ATTACH .
ZMV_JNY_FIELD-ATTACH_LABEL =
ZRAK_T_JNY_FLD-ATTACH_LABEL .
ZMV_JNY_FIELD-ROLLNAME =
ZRAK_T_JNY_FLD-ROLLNAME .
ZMV_JNY_FIELD-SHLP =
ZRAK_T_JNY_FLD-SHLP .
ZMV_JNY_FIELD-ATTACH_TYPES =
ZRAK_T_JNY_FLD-ATTACH_TYPES .
ZMV_JNY_FIELD-ATTACH_MAXMB =
ZRAK_T_JNY_FLD-ATTACH_MAXMB .
ZMV_JNY_FIELD-ATTACH_MULTI =
ZRAK_T_JNY_FLD-ATTACH_MULTI .
ZMV_JNY_FIELD-ZLABEL_AR =
ZRAK_T_JNY_FLD-ZLABEL_AR .
ZMV_JNY_FIELD-PLACEHOLDER_AR =
ZRAK_T_JNY_FLD-PLACEHOLDER_AR .
ZMV_JNY_FIELD-MSG_AR =
ZRAK_T_JNY_FLD-MSG_AR .
ZMV_JNY_FIELD-TECH_NAME =
ZRAK_T_JNY_FLD-TECH_NAME .
ZMV_JNY_FIELD-DOMNAME =
ZRAK_T_JNY_FLD-DOMNAME .
    SELECT SINGLE * FROM ZRAK_T_JNY_STEP WHERE
JOURNEY_ID = ZRAK_T_JNY_FLD-JOURNEY_ID AND
STEP_ID = ZRAK_T_JNY_FLD-STEP_ID .
    IF SY-SUBRC EQ 0.
    ENDIF.
<VIM_TOTAL_STRUC> = ZMV_JNY_FIELD.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZMV_JNY_FIELD .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZMV_JNY_FIELD.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZMV_JNY_FIELD-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZRAK_T_JNY_FLD WHERE
  JOURNEY_ID = ZMV_JNY_FIELD-JOURNEY_ID AND
  STEP_ID = ZMV_JNY_FIELD-STEP_ID AND
  FIELD_NAME = ZMV_JNY_FIELD-FIELD_NAME .
    IF SY-SUBRC = 0.
    DELETE ZRAK_T_JNY_FLD .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZRAK_T_JNY_FLD WHERE
  JOURNEY_ID = ZMV_JNY_FIELD-JOURNEY_ID AND
  STEP_ID = ZMV_JNY_FIELD-STEP_ID AND
  FIELD_NAME = ZMV_JNY_FIELD-FIELD_NAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZRAK_T_JNY_FLD.
    ENDIF.
ZRAK_T_JNY_FLD-MANDT =
ZMV_JNY_FIELD-MANDT .
ZRAK_T_JNY_FLD-JOURNEY_ID =
ZMV_JNY_FIELD-JOURNEY_ID .
ZRAK_T_JNY_FLD-STEP_ID =
ZMV_JNY_FIELD-STEP_ID .
ZRAK_T_JNY_FLD-FIELD_NAME =
ZMV_JNY_FIELD-FIELD_NAME .
ZRAK_T_JNY_FLD-SEQNR =
ZMV_JNY_FIELD-SEQNR .
ZRAK_T_JNY_FLD-ZLABEL =
ZMV_JNY_FIELD-ZLABEL .
ZRAK_T_JNY_FLD-FTYPE =
ZMV_JNY_FIELD-FTYPE .
ZRAK_T_JNY_FLD-PLACEHOLDER =
ZMV_JNY_FIELD-PLACEHOLDER .
ZRAK_T_JNY_FLD-DEFAULT_VAL =
ZMV_JNY_FIELD-DEFAULT_VAL .
ZRAK_T_JNY_FLD-FGROUP =
ZMV_JNY_FIELD-FGROUP .
ZRAK_T_JNY_FLD-ZSECTION =
ZMV_JNY_FIELD-ZSECTION .
ZRAK_T_JNY_FLD-FSTATE =
ZMV_JNY_FIELD-FSTATE .
ZRAK_T_JNY_FLD-WIDTH =
ZMV_JNY_FIELD-WIDTH .
ZRAK_T_JNY_FLD-HIDDEN =
ZMV_JNY_FIELD-HIDDEN .
ZRAK_T_JNY_FLD-READONLY =
ZMV_JNY_FIELD-READONLY .
ZRAK_T_JNY_FLD-REQUIRED =
ZMV_JNY_FIELD-REQUIRED .
ZRAK_T_JNY_FLD-REGEX =
ZMV_JNY_FIELD-REGEX .
ZRAK_T_JNY_FLD-MIN_LEN =
ZMV_JNY_FIELD-MIN_LEN .
ZRAK_T_JNY_FLD-MAX_LEN =
ZMV_JNY_FIELD-MAX_LEN .
ZRAK_T_JNY_FLD-MIN_VAL =
ZMV_JNY_FIELD-MIN_VAL .
ZRAK_T_JNY_FLD-MAX_VAL =
ZMV_JNY_FIELD-MAX_VAL .
ZRAK_T_JNY_FLD-MSG =
ZMV_JNY_FIELD-MSG .
ZRAK_T_JNY_FLD-HAS_ATTACH =
ZMV_JNY_FIELD-HAS_ATTACH .
ZRAK_T_JNY_FLD-ATTACH_LABEL =
ZMV_JNY_FIELD-ATTACH_LABEL .
ZRAK_T_JNY_FLD-ROLLNAME =
ZMV_JNY_FIELD-ROLLNAME .
ZRAK_T_JNY_FLD-SHLP =
ZMV_JNY_FIELD-SHLP .
ZRAK_T_JNY_FLD-ATTACH_TYPES =
ZMV_JNY_FIELD-ATTACH_TYPES .
ZRAK_T_JNY_FLD-ATTACH_MAXMB =
ZMV_JNY_FIELD-ATTACH_MAXMB .
ZRAK_T_JNY_FLD-ATTACH_MULTI =
ZMV_JNY_FIELD-ATTACH_MULTI .
ZRAK_T_JNY_FLD-ZLABEL_AR =
ZMV_JNY_FIELD-ZLABEL_AR .
ZRAK_T_JNY_FLD-PLACEHOLDER_AR =
ZMV_JNY_FIELD-PLACEHOLDER_AR .
ZRAK_T_JNY_FLD-MSG_AR =
ZMV_JNY_FIELD-MSG_AR .
ZRAK_T_JNY_FLD-TECH_NAME =
ZMV_JNY_FIELD-TECH_NAME .
ZRAK_T_JNY_FLD-DOMNAME =
ZMV_JNY_FIELD-DOMNAME .
    IF SY-SUBRC = 0.
    UPDATE ZRAK_T_JNY_FLD ##WARN_OK.
    ELSE.
    INSERT ZRAK_T_JNY_FLD .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZMV_JNY_FIELD-UPD_FLAG,
STATUS_ZMV_JNY_FIELD-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZMV_JNY_FIELD.
  SELECT SINGLE * FROM ZRAK_T_JNY_FLD WHERE
JOURNEY_ID = ZMV_JNY_FIELD-JOURNEY_ID AND
STEP_ID = ZMV_JNY_FIELD-STEP_ID AND
FIELD_NAME = ZMV_JNY_FIELD-FIELD_NAME .
ZMV_JNY_FIELD-MANDT =
ZRAK_T_JNY_FLD-MANDT .
ZMV_JNY_FIELD-JOURNEY_ID =
ZRAK_T_JNY_FLD-JOURNEY_ID .
ZMV_JNY_FIELD-STEP_ID =
ZRAK_T_JNY_FLD-STEP_ID .
ZMV_JNY_FIELD-FIELD_NAME =
ZRAK_T_JNY_FLD-FIELD_NAME .
ZMV_JNY_FIELD-SEQNR =
ZRAK_T_JNY_FLD-SEQNR .
ZMV_JNY_FIELD-ZLABEL =
ZRAK_T_JNY_FLD-ZLABEL .
ZMV_JNY_FIELD-FTYPE =
ZRAK_T_JNY_FLD-FTYPE .
ZMV_JNY_FIELD-PLACEHOLDER =
ZRAK_T_JNY_FLD-PLACEHOLDER .
ZMV_JNY_FIELD-DEFAULT_VAL =
ZRAK_T_JNY_FLD-DEFAULT_VAL .
ZMV_JNY_FIELD-FGROUP =
ZRAK_T_JNY_FLD-FGROUP .
ZMV_JNY_FIELD-ZSECTION =
ZRAK_T_JNY_FLD-ZSECTION .
ZMV_JNY_FIELD-FSTATE =
ZRAK_T_JNY_FLD-FSTATE .
ZMV_JNY_FIELD-WIDTH =
ZRAK_T_JNY_FLD-WIDTH .
ZMV_JNY_FIELD-HIDDEN =
ZRAK_T_JNY_FLD-HIDDEN .
ZMV_JNY_FIELD-READONLY =
ZRAK_T_JNY_FLD-READONLY .
ZMV_JNY_FIELD-REQUIRED =
ZRAK_T_JNY_FLD-REQUIRED .
ZMV_JNY_FIELD-REGEX =
ZRAK_T_JNY_FLD-REGEX .
ZMV_JNY_FIELD-MIN_LEN =
ZRAK_T_JNY_FLD-MIN_LEN .
ZMV_JNY_FIELD-MAX_LEN =
ZRAK_T_JNY_FLD-MAX_LEN .
ZMV_JNY_FIELD-MIN_VAL =
ZRAK_T_JNY_FLD-MIN_VAL .
ZMV_JNY_FIELD-MAX_VAL =
ZRAK_T_JNY_FLD-MAX_VAL .
ZMV_JNY_FIELD-MSG =
ZRAK_T_JNY_FLD-MSG .
ZMV_JNY_FIELD-HAS_ATTACH =
ZRAK_T_JNY_FLD-HAS_ATTACH .
ZMV_JNY_FIELD-ATTACH_LABEL =
ZRAK_T_JNY_FLD-ATTACH_LABEL .
ZMV_JNY_FIELD-ROLLNAME =
ZRAK_T_JNY_FLD-ROLLNAME .
ZMV_JNY_FIELD-SHLP =
ZRAK_T_JNY_FLD-SHLP .
ZMV_JNY_FIELD-ATTACH_TYPES =
ZRAK_T_JNY_FLD-ATTACH_TYPES .
ZMV_JNY_FIELD-ATTACH_MAXMB =
ZRAK_T_JNY_FLD-ATTACH_MAXMB .
ZMV_JNY_FIELD-ATTACH_MULTI =
ZRAK_T_JNY_FLD-ATTACH_MULTI .
ZMV_JNY_FIELD-ZLABEL_AR =
ZRAK_T_JNY_FLD-ZLABEL_AR .
ZMV_JNY_FIELD-PLACEHOLDER_AR =
ZRAK_T_JNY_FLD-PLACEHOLDER_AR .
ZMV_JNY_FIELD-MSG_AR =
ZRAK_T_JNY_FLD-MSG_AR .
ZMV_JNY_FIELD-TECH_NAME =
ZRAK_T_JNY_FLD-TECH_NAME .
ZMV_JNY_FIELD-DOMNAME =
ZRAK_T_JNY_FLD-DOMNAME .
    SELECT SINGLE * FROM ZRAK_T_JNY_STEP WHERE
JOURNEY_ID = ZRAK_T_JNY_FLD-JOURNEY_ID AND
STEP_ID = ZRAK_T_JNY_FLD-STEP_ID .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZMV_JNY_FIELD USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZMV_JNY_FIELD-JOURNEY_ID TO
ZRAK_T_JNY_FLD-JOURNEY_ID .
MOVE ZMV_JNY_FIELD-STEP_ID TO
ZRAK_T_JNY_FLD-STEP_ID .
MOVE ZMV_JNY_FIELD-FIELD_NAME TO
ZRAK_T_JNY_FLD-FIELD_NAME .
MOVE ZMV_JNY_FIELD-MANDT TO
ZRAK_T_JNY_FLD-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZRAK_T_JNY_FLD'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZRAK_T_JNY_FLD TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZRAK_T_JNY_FLD'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZMV_JNY_FIELD USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZRAK_T_JNY_FLD-MANDT =
ZMV_JNY_FIELD-MANDT .
ZRAK_T_JNY_FLD-JOURNEY_ID =
ZMV_JNY_FIELD-JOURNEY_ID .
ZRAK_T_JNY_FLD-STEP_ID =
ZMV_JNY_FIELD-STEP_ID .
ZRAK_T_JNY_FLD-FIELD_NAME =
ZMV_JNY_FIELD-FIELD_NAME .
ZRAK_T_JNY_FLD-SEQNR =
ZMV_JNY_FIELD-SEQNR .
ZRAK_T_JNY_FLD-ZLABEL =
ZMV_JNY_FIELD-ZLABEL .
ZRAK_T_JNY_FLD-FTYPE =
ZMV_JNY_FIELD-FTYPE .
ZRAK_T_JNY_FLD-PLACEHOLDER =
ZMV_JNY_FIELD-PLACEHOLDER .
ZRAK_T_JNY_FLD-DEFAULT_VAL =
ZMV_JNY_FIELD-DEFAULT_VAL .
ZRAK_T_JNY_FLD-FGROUP =
ZMV_JNY_FIELD-FGROUP .
ZRAK_T_JNY_FLD-ZSECTION =
ZMV_JNY_FIELD-ZSECTION .
ZRAK_T_JNY_FLD-FSTATE =
ZMV_JNY_FIELD-FSTATE .
ZRAK_T_JNY_FLD-WIDTH =
ZMV_JNY_FIELD-WIDTH .
ZRAK_T_JNY_FLD-HIDDEN =
ZMV_JNY_FIELD-HIDDEN .
ZRAK_T_JNY_FLD-READONLY =
ZMV_JNY_FIELD-READONLY .
ZRAK_T_JNY_FLD-REQUIRED =
ZMV_JNY_FIELD-REQUIRED .
ZRAK_T_JNY_FLD-REGEX =
ZMV_JNY_FIELD-REGEX .
ZRAK_T_JNY_FLD-MIN_LEN =
ZMV_JNY_FIELD-MIN_LEN .
ZRAK_T_JNY_FLD-MAX_LEN =
ZMV_JNY_FIELD-MAX_LEN .
ZRAK_T_JNY_FLD-MIN_VAL =
ZMV_JNY_FIELD-MIN_VAL .
ZRAK_T_JNY_FLD-MAX_VAL =
ZMV_JNY_FIELD-MAX_VAL .
ZRAK_T_JNY_FLD-MSG =
ZMV_JNY_FIELD-MSG .
ZRAK_T_JNY_FLD-HAS_ATTACH =
ZMV_JNY_FIELD-HAS_ATTACH .
ZRAK_T_JNY_FLD-ATTACH_LABEL =
ZMV_JNY_FIELD-ATTACH_LABEL .
ZRAK_T_JNY_FLD-ROLLNAME =
ZMV_JNY_FIELD-ROLLNAME .
ZRAK_T_JNY_FLD-SHLP =
ZMV_JNY_FIELD-SHLP .
ZRAK_T_JNY_FLD-ATTACH_TYPES =
ZMV_JNY_FIELD-ATTACH_TYPES .
ZRAK_T_JNY_FLD-ATTACH_MAXMB =
ZMV_JNY_FIELD-ATTACH_MAXMB .
ZRAK_T_JNY_FLD-ATTACH_MULTI =
ZMV_JNY_FIELD-ATTACH_MULTI .
ZRAK_T_JNY_FLD-ZLABEL_AR =
ZMV_JNY_FIELD-ZLABEL_AR .
ZRAK_T_JNY_FLD-PLACEHOLDER_AR =
ZMV_JNY_FIELD-PLACEHOLDER_AR .
ZRAK_T_JNY_FLD-MSG_AR =
ZMV_JNY_FIELD-MSG_AR .
ZRAK_T_JNY_FLD-TECH_NAME =
ZMV_JNY_FIELD-TECH_NAME .
ZRAK_T_JNY_FLD-DOMNAME =
ZMV_JNY_FIELD-DOMNAME .
    SELECT SINGLE * FROM ZRAK_T_JNY_STEP WHERE
JOURNEY_ID = ZRAK_T_JNY_FLD-JOURNEY_ID AND
STEP_ID = ZRAK_T_JNY_FLD-STEP_ID .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
ENDFORM.
