*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZMV_JNY_STEP....................................*
FORM GET_DATA_ZMV_JNY_STEP.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZRAK_T_JNY_STEP WHERE
(VIM_WHERETAB) .
    CLEAR ZMV_JNY_STEP .
ZMV_JNY_STEP-MANDT =
ZRAK_T_JNY_STEP-MANDT .
ZMV_JNY_STEP-JOURNEY_ID =
ZRAK_T_JNY_STEP-JOURNEY_ID .
ZMV_JNY_STEP-STEP_ID =
ZRAK_T_JNY_STEP-STEP_ID .
ZMV_JNY_STEP-SEQNR =
ZRAK_T_JNY_STEP-SEQNR .
ZMV_JNY_STEP-TITLE =
ZRAK_T_JNY_STEP-TITLE .
ZMV_JNY_STEP-ICON =
ZRAK_T_JNY_STEP-ICON .
ZMV_JNY_STEP-COLUMNS =
ZRAK_T_JNY_STEP-COLUMNS .
ZMV_JNY_STEP-TITLE_AR =
ZRAK_T_JNY_STEP-TITLE_AR .
ZMV_JNY_STEP-BKND_SCREEN =
ZRAK_T_JNY_STEP-BKND_SCREEN .
ZMV_JNY_STEP-ACTIVE =
ZRAK_T_JNY_STEP-ACTIVE .
ZMV_JNY_STEP-NEXT_REQUIRES =
ZRAK_T_JNY_STEP-NEXT_REQUIRES .
ZMV_JNY_STEP-NO_FORWARD =
ZRAK_T_JNY_STEP-NO_FORWARD .
    SELECT SINGLE * FROM ZRAK_T_JNY WHERE
JOURNEY_ID = ZRAK_T_JNY_STEP-JOURNEY_ID .
    IF SY-SUBRC EQ 0.
    ENDIF.
<VIM_TOTAL_STRUC> = ZMV_JNY_STEP.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZMV_JNY_STEP .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZMV_JNY_STEP.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZMV_JNY_STEP-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZRAK_T_JNY_STEP WHERE
  JOURNEY_ID = ZMV_JNY_STEP-JOURNEY_ID AND
  STEP_ID = ZMV_JNY_STEP-STEP_ID .
    IF SY-SUBRC = 0.
    DELETE ZRAK_T_JNY_STEP .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZRAK_T_JNY_STEP WHERE
  JOURNEY_ID = ZMV_JNY_STEP-JOURNEY_ID AND
  STEP_ID = ZMV_JNY_STEP-STEP_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZRAK_T_JNY_STEP.
    ENDIF.
ZRAK_T_JNY_STEP-MANDT =
ZMV_JNY_STEP-MANDT .
ZRAK_T_JNY_STEP-JOURNEY_ID =
ZMV_JNY_STEP-JOURNEY_ID .
ZRAK_T_JNY_STEP-STEP_ID =
ZMV_JNY_STEP-STEP_ID .
ZRAK_T_JNY_STEP-SEQNR =
ZMV_JNY_STEP-SEQNR .
ZRAK_T_JNY_STEP-TITLE =
ZMV_JNY_STEP-TITLE .
ZRAK_T_JNY_STEP-ICON =
ZMV_JNY_STEP-ICON .
ZRAK_T_JNY_STEP-COLUMNS =
ZMV_JNY_STEP-COLUMNS .
ZRAK_T_JNY_STEP-TITLE_AR =
ZMV_JNY_STEP-TITLE_AR .
ZRAK_T_JNY_STEP-BKND_SCREEN =
ZMV_JNY_STEP-BKND_SCREEN .
ZRAK_T_JNY_STEP-ACTIVE =
ZMV_JNY_STEP-ACTIVE .
ZRAK_T_JNY_STEP-NEXT_REQUIRES =
ZMV_JNY_STEP-NEXT_REQUIRES .
ZRAK_T_JNY_STEP-NO_FORWARD =
ZMV_JNY_STEP-NO_FORWARD .
    IF SY-SUBRC = 0.
    UPDATE ZRAK_T_JNY_STEP ##WARN_OK.
    ELSE.
    INSERT ZRAK_T_JNY_STEP .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZMV_JNY_STEP-UPD_FLAG,
STATUS_ZMV_JNY_STEP-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZMV_JNY_STEP.
  SELECT SINGLE * FROM ZRAK_T_JNY_STEP WHERE
JOURNEY_ID = ZMV_JNY_STEP-JOURNEY_ID AND
STEP_ID = ZMV_JNY_STEP-STEP_ID .
ZMV_JNY_STEP-MANDT =
ZRAK_T_JNY_STEP-MANDT .
ZMV_JNY_STEP-JOURNEY_ID =
ZRAK_T_JNY_STEP-JOURNEY_ID .
ZMV_JNY_STEP-STEP_ID =
ZRAK_T_JNY_STEP-STEP_ID .
ZMV_JNY_STEP-SEQNR =
ZRAK_T_JNY_STEP-SEQNR .
ZMV_JNY_STEP-TITLE =
ZRAK_T_JNY_STEP-TITLE .
ZMV_JNY_STEP-ICON =
ZRAK_T_JNY_STEP-ICON .
ZMV_JNY_STEP-COLUMNS =
ZRAK_T_JNY_STEP-COLUMNS .
ZMV_JNY_STEP-TITLE_AR =
ZRAK_T_JNY_STEP-TITLE_AR .
ZMV_JNY_STEP-BKND_SCREEN =
ZRAK_T_JNY_STEP-BKND_SCREEN .
ZMV_JNY_STEP-ACTIVE =
ZRAK_T_JNY_STEP-ACTIVE .
ZMV_JNY_STEP-NEXT_REQUIRES =
ZRAK_T_JNY_STEP-NEXT_REQUIRES .
ZMV_JNY_STEP-NO_FORWARD =
ZRAK_T_JNY_STEP-NO_FORWARD .
    SELECT SINGLE * FROM ZRAK_T_JNY WHERE
JOURNEY_ID = ZRAK_T_JNY_STEP-JOURNEY_ID .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZMV_JNY_STEP USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZMV_JNY_STEP-JOURNEY_ID TO
ZRAK_T_JNY_STEP-JOURNEY_ID .
MOVE ZMV_JNY_STEP-STEP_ID TO
ZRAK_T_JNY_STEP-STEP_ID .
MOVE ZMV_JNY_STEP-MANDT TO
ZRAK_T_JNY_STEP-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZRAK_T_JNY_STEP'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZRAK_T_JNY_STEP TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZRAK_T_JNY_STEP'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZMV_JNY_STEP USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZRAK_T_JNY_STEP-MANDT =
ZMV_JNY_STEP-MANDT .
ZRAK_T_JNY_STEP-JOURNEY_ID =
ZMV_JNY_STEP-JOURNEY_ID .
ZRAK_T_JNY_STEP-STEP_ID =
ZMV_JNY_STEP-STEP_ID .
ZRAK_T_JNY_STEP-SEQNR =
ZMV_JNY_STEP-SEQNR .
ZRAK_T_JNY_STEP-TITLE =
ZMV_JNY_STEP-TITLE .
ZRAK_T_JNY_STEP-ICON =
ZMV_JNY_STEP-ICON .
ZRAK_T_JNY_STEP-COLUMNS =
ZMV_JNY_STEP-COLUMNS .
ZRAK_T_JNY_STEP-TITLE_AR =
ZMV_JNY_STEP-TITLE_AR .
ZRAK_T_JNY_STEP-BKND_SCREEN =
ZMV_JNY_STEP-BKND_SCREEN .
ZRAK_T_JNY_STEP-ACTIVE =
ZMV_JNY_STEP-ACTIVE .
ZRAK_T_JNY_STEP-NEXT_REQUIRES =
ZMV_JNY_STEP-NEXT_REQUIRES .
ZRAK_T_JNY_STEP-NO_FORWARD =
ZMV_JNY_STEP-NO_FORWARD .
    SELECT SINGLE * FROM ZRAK_T_JNY WHERE
JOURNEY_ID = ZRAK_T_JNY_STEP-JOURNEY_ID .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
ENDFORM.
