*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZMV_JNY_COL.....................................*
FORM GET_DATA_ZMV_JNY_COL.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZRAK_T_JNY_COL WHERE
(VIM_WHERETAB) .
    CLEAR ZMV_JNY_COL .
ZMV_JNY_COL-MANDT =
ZRAK_T_JNY_COL-MANDT .
ZMV_JNY_COL-JOURNEY_ID =
ZRAK_T_JNY_COL-JOURNEY_ID .
ZMV_JNY_COL-STEP_ID =
ZRAK_T_JNY_COL-STEP_ID .
ZMV_JNY_COL-FIELD_NAME =
ZRAK_T_JNY_COL-FIELD_NAME .
ZMV_JNY_COL-COL_NAME =
ZRAK_T_JNY_COL-COL_NAME .
ZMV_JNY_COL-SEQNR =
ZRAK_T_JNY_COL-SEQNR .
ZMV_JNY_COL-ZLABEL =
ZRAK_T_JNY_COL-ZLABEL .
ZMV_JNY_COL-ZLABEL_AR =
ZRAK_T_JNY_COL-ZLABEL_AR .
ZMV_JNY_COL-CTRL =
ZRAK_T_JNY_COL-CTRL .
ZMV_JNY_COL-SHLP =
ZRAK_T_JNY_COL-SHLP .
ZMV_JNY_COL-ROLLNAME =
ZRAK_T_JNY_COL-ROLLNAME .
ZMV_JNY_COL-WIDTH =
ZRAK_T_JNY_COL-WIDTH .
ZMV_JNY_COL-ALIGN =
ZRAK_T_JNY_COL-ALIGN .
ZMV_JNY_COL-HIDDEN =
ZRAK_T_JNY_COL-HIDDEN .
ZMV_JNY_COL-PINNED =
ZRAK_T_JNY_COL-PINNED .
ZMV_JNY_COL-READONLY =
ZRAK_T_JNY_COL-READONLY .
ZMV_JNY_COL-REQUIRED =
ZRAK_T_JNY_COL-REQUIRED .
ZMV_JNY_COL-DECIMALS =
ZRAK_T_JNY_COL-DECIMALS .
ZMV_JNY_COL-MAXLEN =
ZRAK_T_JNY_COL-MAXLEN .
ZMV_JNY_COL-TOTAL =
ZRAK_T_JNY_COL-TOTAL .
    SELECT SINGLE * FROM ZRAK_T_JNY_FLD WHERE
JOURNEY_ID = ZRAK_T_JNY_COL-JOURNEY_ID AND
STEP_ID = ZRAK_T_JNY_COL-STEP_ID AND
FIELD_NAME = ZRAK_T_JNY_COL-FIELD_NAME .
    IF SY-SUBRC EQ 0.
    ENDIF.
<VIM_TOTAL_STRUC> = ZMV_JNY_COL.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZMV_JNY_COL .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZMV_JNY_COL.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZMV_JNY_COL-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZRAK_T_JNY_COL WHERE
  JOURNEY_ID = ZMV_JNY_COL-JOURNEY_ID AND
  STEP_ID = ZMV_JNY_COL-STEP_ID AND
  FIELD_NAME = ZMV_JNY_COL-FIELD_NAME AND
  COL_NAME = ZMV_JNY_COL-COL_NAME .
    IF SY-SUBRC = 0.
    DELETE ZRAK_T_JNY_COL .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZRAK_T_JNY_COL WHERE
  JOURNEY_ID = ZMV_JNY_COL-JOURNEY_ID AND
  STEP_ID = ZMV_JNY_COL-STEP_ID AND
  FIELD_NAME = ZMV_JNY_COL-FIELD_NAME AND
  COL_NAME = ZMV_JNY_COL-COL_NAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZRAK_T_JNY_COL.
    ENDIF.
ZRAK_T_JNY_COL-MANDT =
ZMV_JNY_COL-MANDT .
ZRAK_T_JNY_COL-JOURNEY_ID =
ZMV_JNY_COL-JOURNEY_ID .
ZRAK_T_JNY_COL-STEP_ID =
ZMV_JNY_COL-STEP_ID .
ZRAK_T_JNY_COL-FIELD_NAME =
ZMV_JNY_COL-FIELD_NAME .
ZRAK_T_JNY_COL-COL_NAME =
ZMV_JNY_COL-COL_NAME .
ZRAK_T_JNY_COL-SEQNR =
ZMV_JNY_COL-SEQNR .
ZRAK_T_JNY_COL-ZLABEL =
ZMV_JNY_COL-ZLABEL .
ZRAK_T_JNY_COL-ZLABEL_AR =
ZMV_JNY_COL-ZLABEL_AR .
ZRAK_T_JNY_COL-CTRL =
ZMV_JNY_COL-CTRL .
ZRAK_T_JNY_COL-SHLP =
ZMV_JNY_COL-SHLP .
ZRAK_T_JNY_COL-ROLLNAME =
ZMV_JNY_COL-ROLLNAME .
ZRAK_T_JNY_COL-WIDTH =
ZMV_JNY_COL-WIDTH .
ZRAK_T_JNY_COL-ALIGN =
ZMV_JNY_COL-ALIGN .
ZRAK_T_JNY_COL-HIDDEN =
ZMV_JNY_COL-HIDDEN .
ZRAK_T_JNY_COL-PINNED =
ZMV_JNY_COL-PINNED .
ZRAK_T_JNY_COL-READONLY =
ZMV_JNY_COL-READONLY .
ZRAK_T_JNY_COL-REQUIRED =
ZMV_JNY_COL-REQUIRED .
ZRAK_T_JNY_COL-DECIMALS =
ZMV_JNY_COL-DECIMALS .
ZRAK_T_JNY_COL-MAXLEN =
ZMV_JNY_COL-MAXLEN .
ZRAK_T_JNY_COL-TOTAL =
ZMV_JNY_COL-TOTAL .
    IF SY-SUBRC = 0.
    UPDATE ZRAK_T_JNY_COL ##WARN_OK.
    ELSE.
    INSERT ZRAK_T_JNY_COL .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZMV_JNY_COL-UPD_FLAG,
STATUS_ZMV_JNY_COL-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZMV_JNY_COL.
  SELECT SINGLE * FROM ZRAK_T_JNY_COL WHERE
JOURNEY_ID = ZMV_JNY_COL-JOURNEY_ID AND
STEP_ID = ZMV_JNY_COL-STEP_ID AND
FIELD_NAME = ZMV_JNY_COL-FIELD_NAME AND
COL_NAME = ZMV_JNY_COL-COL_NAME .
ZMV_JNY_COL-MANDT =
ZRAK_T_JNY_COL-MANDT .
ZMV_JNY_COL-JOURNEY_ID =
ZRAK_T_JNY_COL-JOURNEY_ID .
ZMV_JNY_COL-STEP_ID =
ZRAK_T_JNY_COL-STEP_ID .
ZMV_JNY_COL-FIELD_NAME =
ZRAK_T_JNY_COL-FIELD_NAME .
ZMV_JNY_COL-COL_NAME =
ZRAK_T_JNY_COL-COL_NAME .
ZMV_JNY_COL-SEQNR =
ZRAK_T_JNY_COL-SEQNR .
ZMV_JNY_COL-ZLABEL =
ZRAK_T_JNY_COL-ZLABEL .
ZMV_JNY_COL-ZLABEL_AR =
ZRAK_T_JNY_COL-ZLABEL_AR .
ZMV_JNY_COL-CTRL =
ZRAK_T_JNY_COL-CTRL .
ZMV_JNY_COL-SHLP =
ZRAK_T_JNY_COL-SHLP .
ZMV_JNY_COL-ROLLNAME =
ZRAK_T_JNY_COL-ROLLNAME .
ZMV_JNY_COL-WIDTH =
ZRAK_T_JNY_COL-WIDTH .
ZMV_JNY_COL-ALIGN =
ZRAK_T_JNY_COL-ALIGN .
ZMV_JNY_COL-HIDDEN =
ZRAK_T_JNY_COL-HIDDEN .
ZMV_JNY_COL-PINNED =
ZRAK_T_JNY_COL-PINNED .
ZMV_JNY_COL-READONLY =
ZRAK_T_JNY_COL-READONLY .
ZMV_JNY_COL-REQUIRED =
ZRAK_T_JNY_COL-REQUIRED .
ZMV_JNY_COL-DECIMALS =
ZRAK_T_JNY_COL-DECIMALS .
ZMV_JNY_COL-MAXLEN =
ZRAK_T_JNY_COL-MAXLEN .
ZMV_JNY_COL-TOTAL =
ZRAK_T_JNY_COL-TOTAL .
    SELECT SINGLE * FROM ZRAK_T_JNY_FLD WHERE
JOURNEY_ID = ZRAK_T_JNY_COL-JOURNEY_ID AND
STEP_ID = ZRAK_T_JNY_COL-STEP_ID AND
FIELD_NAME = ZRAK_T_JNY_COL-FIELD_NAME .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZMV_JNY_COL USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZMV_JNY_COL-JOURNEY_ID TO
ZRAK_T_JNY_COL-JOURNEY_ID .
MOVE ZMV_JNY_COL-STEP_ID TO
ZRAK_T_JNY_COL-STEP_ID .
MOVE ZMV_JNY_COL-FIELD_NAME TO
ZRAK_T_JNY_COL-FIELD_NAME .
MOVE ZMV_JNY_COL-COL_NAME TO
ZRAK_T_JNY_COL-COL_NAME .
MOVE ZMV_JNY_COL-MANDT TO
ZRAK_T_JNY_COL-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZRAK_T_JNY_COL'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZRAK_T_JNY_COL TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZRAK_T_JNY_COL'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZMV_JNY_COL USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZRAK_T_JNY_COL-MANDT =
ZMV_JNY_COL-MANDT .
ZRAK_T_JNY_COL-JOURNEY_ID =
ZMV_JNY_COL-JOURNEY_ID .
ZRAK_T_JNY_COL-STEP_ID =
ZMV_JNY_COL-STEP_ID .
ZRAK_T_JNY_COL-FIELD_NAME =
ZMV_JNY_COL-FIELD_NAME .
ZRAK_T_JNY_COL-COL_NAME =
ZMV_JNY_COL-COL_NAME .
ZRAK_T_JNY_COL-SEQNR =
ZMV_JNY_COL-SEQNR .
ZRAK_T_JNY_COL-ZLABEL =
ZMV_JNY_COL-ZLABEL .
ZRAK_T_JNY_COL-ZLABEL_AR =
ZMV_JNY_COL-ZLABEL_AR .
ZRAK_T_JNY_COL-CTRL =
ZMV_JNY_COL-CTRL .
ZRAK_T_JNY_COL-SHLP =
ZMV_JNY_COL-SHLP .
ZRAK_T_JNY_COL-ROLLNAME =
ZMV_JNY_COL-ROLLNAME .
ZRAK_T_JNY_COL-WIDTH =
ZMV_JNY_COL-WIDTH .
ZRAK_T_JNY_COL-ALIGN =
ZMV_JNY_COL-ALIGN .
ZRAK_T_JNY_COL-HIDDEN =
ZMV_JNY_COL-HIDDEN .
ZRAK_T_JNY_COL-PINNED =
ZMV_JNY_COL-PINNED .
ZRAK_T_JNY_COL-READONLY =
ZMV_JNY_COL-READONLY .
ZRAK_T_JNY_COL-REQUIRED =
ZMV_JNY_COL-REQUIRED .
ZRAK_T_JNY_COL-DECIMALS =
ZMV_JNY_COL-DECIMALS .
ZRAK_T_JNY_COL-MAXLEN =
ZMV_JNY_COL-MAXLEN .
ZRAK_T_JNY_COL-TOTAL =
ZMV_JNY_COL-TOTAL .
    SELECT SINGLE * FROM ZRAK_T_JNY_FLD WHERE
JOURNEY_ID = ZRAK_T_JNY_COL-JOURNEY_ID AND
STEP_ID = ZRAK_T_JNY_COL-STEP_ID AND
FIELD_NAME = ZRAK_T_JNY_COL-FIELD_NAME .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
ENDFORM.
