PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 MODULE sort_table.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZMV_JNY_STEP CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
 MODULE FILL_SUBSTFLDS.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZMV_JNY_STEP-STEP_ID .
    FIELD ZMV_JNY_STEP-SEQNR .
    FIELD ZMV_JNY_STEP-TITLE .
    FIELD ZMV_JNY_STEP-ICON .
    FIELD ZMV_JNY_STEP-COLUMNS .
    FIELD ZMV_JNY_STEP-TITLE_AR .
    FIELD ZMV_JNY_STEP-BKND_SCREEN .
    FIELD ZMV_JNY_STEP-ACTIVE .
    FIELD ZMV_JNY_STEP-NEXT_REQUIRES .
    FIELD ZMV_JNY_STEP-NO_FORWARD .
    FIELD ZMV_JNY_STEP-NO_ACTION .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZMV_JNY_STEP-STEP_ID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
