*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZMV_CJ_LAY......................................*
FORM GET_DATA_ZMV_CJ_LAY.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZRAK_CJ_LAY WHERE
(VIM_WHERETAB) .
    CLEAR ZMV_CJ_LAY .
ZMV_CJ_LAY-MANDT =
ZRAK_CJ_LAY-MANDT .
ZMV_CJ_LAY-JOURNEY =
ZRAK_CJ_LAY-JOURNEY .
ZMV_CJ_LAY-STEP_ID =
ZRAK_CJ_LAY-STEP_ID .
ZMV_CJ_LAY-BLOCK_ID =
ZRAK_CJ_LAY-BLOCK_ID .
ZMV_CJ_LAY-ELEM_ID =
ZRAK_CJ_LAY-ELEM_ID .
ZMV_CJ_LAY-KIND =
ZRAK_CJ_LAY-KIND .
ZMV_CJ_LAY-ROW_NO =
ZRAK_CJ_LAY-ROW_NO .
ZMV_CJ_LAY-COL_START =
ZRAK_CJ_LAY-COL_START .
ZMV_CJ_LAY-COL_SPAN =
ZRAK_CJ_LAY-COL_SPAN .
ZMV_CJ_LAY-LABEL_SPAN =
ZRAK_CJ_LAY-LABEL_SPAN .
ZMV_CJ_LAY-FLOW =
ZRAK_CJ_LAY-FLOW .
ZMV_CJ_LAY-INLINE =
ZRAK_CJ_LAY-INLINE .
ZMV_CJ_LAY-HIDDEN =
ZRAK_CJ_LAY-HIDDEN .
ZMV_CJ_LAY-FIXED =
ZRAK_CJ_LAY-FIXED .
ZMV_CJ_LAY-ALIGN =
ZRAK_CJ_LAY-ALIGN .
ZMV_CJ_LAY-WIDTH =
ZRAK_CJ_LAY-WIDTH .
ZMV_CJ_LAY-CHANGED_BY =
ZRAK_CJ_LAY-CHANGED_BY .
ZMV_CJ_LAY-CHANGED_AT =
ZRAK_CJ_LAY-CHANGED_AT .
    SELECT SINGLE * FROM ZRAK_T_JNY_STEP WHERE
JOURNEY_ID = ZRAK_CJ_LAY-JOURNEY AND
STEP_ID = ZRAK_CJ_LAY-STEP_ID .
    IF SY-SUBRC EQ 0.
    ENDIF.
<VIM_TOTAL_STRUC> = ZMV_CJ_LAY.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZMV_CJ_LAY .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZMV_CJ_LAY.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZMV_CJ_LAY-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZRAK_CJ_LAY WHERE
  JOURNEY = ZMV_CJ_LAY-JOURNEY AND
  STEP_ID = ZMV_CJ_LAY-STEP_ID AND
  BLOCK_ID = ZMV_CJ_LAY-BLOCK_ID AND
  ELEM_ID = ZMV_CJ_LAY-ELEM_ID AND
  KIND = ZMV_CJ_LAY-KIND .
    IF SY-SUBRC = 0.
    DELETE ZRAK_CJ_LAY .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZRAK_CJ_LAY WHERE
  JOURNEY = ZMV_CJ_LAY-JOURNEY AND
  STEP_ID = ZMV_CJ_LAY-STEP_ID AND
  BLOCK_ID = ZMV_CJ_LAY-BLOCK_ID AND
  ELEM_ID = ZMV_CJ_LAY-ELEM_ID AND
  KIND = ZMV_CJ_LAY-KIND .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZRAK_CJ_LAY.
    ENDIF.
ZRAK_CJ_LAY-MANDT =
ZMV_CJ_LAY-MANDT .
ZRAK_CJ_LAY-JOURNEY =
ZMV_CJ_LAY-JOURNEY .
ZRAK_CJ_LAY-STEP_ID =
ZMV_CJ_LAY-STEP_ID .
ZRAK_CJ_LAY-BLOCK_ID =
ZMV_CJ_LAY-BLOCK_ID .
ZRAK_CJ_LAY-ELEM_ID =
ZMV_CJ_LAY-ELEM_ID .
ZRAK_CJ_LAY-KIND =
ZMV_CJ_LAY-KIND .
ZRAK_CJ_LAY-ROW_NO =
ZMV_CJ_LAY-ROW_NO .
ZRAK_CJ_LAY-COL_START =
ZMV_CJ_LAY-COL_START .
ZRAK_CJ_LAY-COL_SPAN =
ZMV_CJ_LAY-COL_SPAN .
ZRAK_CJ_LAY-LABEL_SPAN =
ZMV_CJ_LAY-LABEL_SPAN .
ZRAK_CJ_LAY-FLOW =
ZMV_CJ_LAY-FLOW .
ZRAK_CJ_LAY-INLINE =
ZMV_CJ_LAY-INLINE .
ZRAK_CJ_LAY-HIDDEN =
ZMV_CJ_LAY-HIDDEN .
ZRAK_CJ_LAY-FIXED =
ZMV_CJ_LAY-FIXED .
ZRAK_CJ_LAY-ALIGN =
ZMV_CJ_LAY-ALIGN .
ZRAK_CJ_LAY-WIDTH =
ZMV_CJ_LAY-WIDTH .
ZRAK_CJ_LAY-CHANGED_BY =
ZMV_CJ_LAY-CHANGED_BY .
ZRAK_CJ_LAY-CHANGED_AT =
ZMV_CJ_LAY-CHANGED_AT .
    IF SY-SUBRC = 0.
    UPDATE ZRAK_CJ_LAY ##WARN_OK.
    ELSE.
    INSERT ZRAK_CJ_LAY .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZMV_CJ_LAY-UPD_FLAG,
STATUS_ZMV_CJ_LAY-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZMV_CJ_LAY.
  SELECT SINGLE * FROM ZRAK_CJ_LAY WHERE
JOURNEY = ZMV_CJ_LAY-JOURNEY AND
STEP_ID = ZMV_CJ_LAY-STEP_ID AND
BLOCK_ID = ZMV_CJ_LAY-BLOCK_ID AND
ELEM_ID = ZMV_CJ_LAY-ELEM_ID AND
KIND = ZMV_CJ_LAY-KIND .
ZMV_CJ_LAY-MANDT =
ZRAK_CJ_LAY-MANDT .
ZMV_CJ_LAY-JOURNEY =
ZRAK_CJ_LAY-JOURNEY .
ZMV_CJ_LAY-STEP_ID =
ZRAK_CJ_LAY-STEP_ID .
ZMV_CJ_LAY-BLOCK_ID =
ZRAK_CJ_LAY-BLOCK_ID .
ZMV_CJ_LAY-ELEM_ID =
ZRAK_CJ_LAY-ELEM_ID .
ZMV_CJ_LAY-KIND =
ZRAK_CJ_LAY-KIND .
ZMV_CJ_LAY-ROW_NO =
ZRAK_CJ_LAY-ROW_NO .
ZMV_CJ_LAY-COL_START =
ZRAK_CJ_LAY-COL_START .
ZMV_CJ_LAY-COL_SPAN =
ZRAK_CJ_LAY-COL_SPAN .
ZMV_CJ_LAY-LABEL_SPAN =
ZRAK_CJ_LAY-LABEL_SPAN .
ZMV_CJ_LAY-FLOW =
ZRAK_CJ_LAY-FLOW .
ZMV_CJ_LAY-INLINE =
ZRAK_CJ_LAY-INLINE .
ZMV_CJ_LAY-HIDDEN =
ZRAK_CJ_LAY-HIDDEN .
ZMV_CJ_LAY-FIXED =
ZRAK_CJ_LAY-FIXED .
ZMV_CJ_LAY-ALIGN =
ZRAK_CJ_LAY-ALIGN .
ZMV_CJ_LAY-WIDTH =
ZRAK_CJ_LAY-WIDTH .
ZMV_CJ_LAY-CHANGED_BY =
ZRAK_CJ_LAY-CHANGED_BY .
ZMV_CJ_LAY-CHANGED_AT =
ZRAK_CJ_LAY-CHANGED_AT .
    SELECT SINGLE * FROM ZRAK_T_JNY_STEP WHERE
JOURNEY_ID = ZRAK_CJ_LAY-JOURNEY AND
STEP_ID = ZRAK_CJ_LAY-STEP_ID .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZMV_CJ_LAY USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZMV_CJ_LAY-JOURNEY TO
ZRAK_CJ_LAY-JOURNEY .
MOVE ZMV_CJ_LAY-STEP_ID TO
ZRAK_CJ_LAY-STEP_ID .
MOVE ZMV_CJ_LAY-BLOCK_ID TO
ZRAK_CJ_LAY-BLOCK_ID .
MOVE ZMV_CJ_LAY-ELEM_ID TO
ZRAK_CJ_LAY-ELEM_ID .
MOVE ZMV_CJ_LAY-KIND TO
ZRAK_CJ_LAY-KIND .
MOVE ZMV_CJ_LAY-MANDT TO
ZRAK_CJ_LAY-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZRAK_CJ_LAY'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZRAK_CJ_LAY TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZRAK_CJ_LAY'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZMV_CJ_LAY USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZRAK_CJ_LAY-MANDT =
ZMV_CJ_LAY-MANDT .
ZRAK_CJ_LAY-JOURNEY =
ZMV_CJ_LAY-JOURNEY .
ZRAK_CJ_LAY-STEP_ID =
ZMV_CJ_LAY-STEP_ID .
ZRAK_CJ_LAY-BLOCK_ID =
ZMV_CJ_LAY-BLOCK_ID .
ZRAK_CJ_LAY-ELEM_ID =
ZMV_CJ_LAY-ELEM_ID .
ZRAK_CJ_LAY-KIND =
ZMV_CJ_LAY-KIND .
ZRAK_CJ_LAY-ROW_NO =
ZMV_CJ_LAY-ROW_NO .
ZRAK_CJ_LAY-COL_START =
ZMV_CJ_LAY-COL_START .
ZRAK_CJ_LAY-COL_SPAN =
ZMV_CJ_LAY-COL_SPAN .
ZRAK_CJ_LAY-LABEL_SPAN =
ZMV_CJ_LAY-LABEL_SPAN .
ZRAK_CJ_LAY-FLOW =
ZMV_CJ_LAY-FLOW .
ZRAK_CJ_LAY-INLINE =
ZMV_CJ_LAY-INLINE .
ZRAK_CJ_LAY-HIDDEN =
ZMV_CJ_LAY-HIDDEN .
ZRAK_CJ_LAY-FIXED =
ZMV_CJ_LAY-FIXED .
ZRAK_CJ_LAY-ALIGN =
ZMV_CJ_LAY-ALIGN .
ZRAK_CJ_LAY-WIDTH =
ZMV_CJ_LAY-WIDTH .
ZRAK_CJ_LAY-CHANGED_BY =
ZMV_CJ_LAY-CHANGED_BY .
ZRAK_CJ_LAY-CHANGED_AT =
ZMV_CJ_LAY-CHANGED_AT .
    SELECT SINGLE * FROM ZRAK_T_JNY_STEP WHERE
JOURNEY_ID = ZRAK_CJ_LAY-JOURNEY AND
STEP_ID = ZRAK_CJ_LAY-STEP_ID .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
ENDFORM.
